apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
    env: {{ .Values.env.name }}
  name: {{ .Values.app.name }}
  namespace: {{ .Values.env.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      deployment: {{ .Values.app.name }}
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: {{ .Values.app.name }}
        deployment: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.image.name }}:{{ .Values.image.version }}
        name: {{ .Values.app.name }}
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.liveness.path }}
            port: 8080
        readinessProbe:
          httpGet:
            path: {{ .Values.readiness.path }}
            port: 8080
